TurkTicaretCRM.TT.Mvc/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurkTicaretCRM.TT.Bussiness.Abstract;
using TurkTicaretCRM.TT.Entities.Concrete;

namespace TurkTicaretCRM.TT.Mvc.Controllers
{
    public class CustomerController : Controller
    {
        ICustomerService _customerService;
        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CustomerManage()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CustomerProfile(string id)
        {
            Customer result = _customerService.GetById(int.Parse(id));
            ViewData.Add("Customer", result);
            return View();
        }

        public ActionResult GetAllCustomers()
        {
            var result = _customerService.GetAll();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult AddCustomer(Customer customer)
        {
            customer.RegistrationDate = DateTime.Now;
            customer.UpdateDate = DateTime.Now;
            var result = _customerService.Add(customer);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult DeleteCustomer(string id)
        {
            var result = _customerService.DeleteById(int.Parse(id));
            return Json(result);
        }

    }
}

TurkTicaretCRM.TT.Mvc/Controllers/DebitManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurkTicaretCRM.TT.Bussiness.Abstract;
using TurkTicaretCRM.TT.Entities.Concrete;

namespace TurkTicaretCRM.TT.Mvc.Controllers
{
    public class DebitManageController : Controller
    {
        IDebitActivityService _debitActivityService;
        ICustomerDebitService _customerDebitService;
        IDebitService _debitService;

        public DebitManageController(IDebitActivityService debitActivityService, ICustomerDebitService customerDebitService, IDebitService debitService)
        {
            _debitActivityService = debitActivityService;
            _customerDebitService = customerDebitService;
            _debitService = debitService;
        }
        // GET: DebitManage
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DebitManage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddDebit(CustomerDebit customerDebit)
        {
            customerDebit.CustomerDebitStatus = true;
            customerDebit.RegistrationDate = DateTime.Now;
            customerDebit.UpdateDate = DateTime.Now;
            var result = _customerDebitService.Add(customerDebit);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetAllDebitsByCustomerId(int id) {
            var result = _customerDebitService.GetDebitsByCustomerId(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult UpdateCustomerDebitWithActivity(DebitActivity activity)
        {
            _debitActivityService.Add(activity);
            var result = _customerDebitService.UpdateWithActivity(activity);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

TurkTicaretCRM.TT.Mvc/Controllers/DebitTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurkTicaretCRM.TT.Bussiness.Abstract;
using TurkTicaretCRM.TT.Entities.Concrete;

namespace TurkTicaretCRM.TT.Mvc.Controllers
{
    public class DebitTypeController : Controller
    {
        IDebitService _debitService;
        public DebitTypeController(IDebitService debitService)
        {
            _debitService = debitService;
        }
        // GET: DebitType
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult DebitTypeManage()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddDebitType(Debit debit)
        {
            var result = _debitService.Add(debit);
            return Json(result);
        }

        public ActionResult GetAllDebits()
        {
            var result = _debitService.GetAll();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

TurkTicaretCRM.TT.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurkTicaretCRM.TT.Bussiness.Abstract;

namespace TurkTicaretCRM.TT.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private ICustomerService _customerService;

        public HomeController(ICustomerService customerService)
        {
            _customerService = customerService;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAllCustomer()
        {
            var result = _customerService.GetById(1).CustomerID;
            return Json(result, JsonRequestBehavior.AllowGet);
        }


    }
}

TurkTicaretCRM.TT.Mvc/Views/Customer/CustomerManage.cshtml
@{
    ViewBag.Title = "CustomerManage";
}

<div class="container-fluid">
            <!--AddCustomer Button Here-->
    <div class="card-group" >
        <div data-toggle="modal" data-target="#customerModal">
            <a href="#" class="btn btn-success btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-flag"></i>
                </span>
                <span class="text">Müşteri Ekle</span>
            </a>
        </div>
        <div>
            <a id="btnDeleteCustomer" class="btn btn-danger btn-icon-split">
                <span class="icon text-white-50">
                    <i class="fas fa-flag"></i>
                </span>
                <span class="text">Sil</span>
            </a>
        </div>
        
        
    </div>
            <!--Customer Table Here-->
<div class="card shadow mb-4">
   <div class="card-header py-3">
       <h6 class="m-0 font-weight-bold text-primary">Müşteriler Tablosu</h6>
   </div>
   <div class="card-body">
       <div class="table-responsive" style="overflow:auto; height:auto; ">
           
                       <table class="table table-hover" id="dataTable" width="50%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                           <thead>
                               <tr role="row">
                                   <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 38px;">Seç</th>
                                   <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 68px;">İsim</th>
                                   <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 93px;">Soyisim</th>
                                   <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 52px;">Adres</th>
                                   <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 31px;">Telefon</th>
                                   <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending" style="width: 68px;">Kayıt Tarihi</th>
                               </tr>
                           </thead>
                           <tbody>
                           </tbody>
                       </table>
       </div>
   </div>
</div>
    <div>
       
    </div>
        </div>
<!--AddCustomer Modal-->
<div class="modal fade" id="customerModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Müşteri Ekle</h4>
            </div>
            <div class="modal-body">
                    <div class="form-group"><input id="inputCustomerName" class="form-control form-control-user" placeholder="İsim Giriniz..." required /></div>
                    <div class="form-group"><input id="inputCustomerSurname" class="form-control form-control-user" placeholder="Soyisim Giriniz..." required /></div>
                    <div class="form-group"><input id="inputCustomerAddress" class="form-control form-control-user" placeholder="Adres Giriniz" required /></div>
                    <div class="form-group"><input id="inputCustomerPhone" class="form-control form-control-user" placeholder="Telefon Numarası Giriniz" required /></div>
                    <div class="form-group"><input id="inputCustomerEmail" class="form-control form-control-user" placeholder="Email Adresi Giriniz" /></div>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <button id="btnAddCustomer" type="button" class="btn btn-primary" data-dismiss="modal">Ekle</button>
                    <button id="btnCloseCustomerModal" type="button" class="btn btn-primary" data-dismiss="modal">Kapat</button>
                </div>
                
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("tbody > tr").remove();
        createCustomerTable();
    });

    function createCustomerTable() {
        $("tbody > tr").remove();
        $.ajax({
            url: "@Url.Action("GetAllCustomers","Customer")",
            type: "GET",
            dataType: "json",
            success: function (data) {
                $.each(data, function (i, item) {
                    var $tr = $('<tr>').click(function (event) {
            if (event.target.type !== 'checkbox') {
                 $(':checkbox', this).trigger('click');
            }
        }).append(
                        $('<td>').html('<input type="checkbox">'),
                        $('<td>').text(item.CustomerName),
                        $('<td>').text(item.CustomerSurname),
                        $('<td>').text(item.CustomerAddress),
                        $('<td>').text(item.CustomerPhone),
                        $('<td>').text(new Date(parseInt(item.RegistrationDate.substr(6))).toLocaleDateString())
                    ).attr("customerID",item.CustomerID).appendTo("#dataTable"); //.appendTo('#records_table');
                    
                });
            }
        })
    }

    $("#btnAddCustomer").on("click", function () {
        
        $.ajax({
            url: "@Url.Action("AddCustomer","Customer")",
            type: "POST",
            dataType: "json",
            data: {
                CustomerName: $("#inputCustomerName").val(),
                CustomerSurname: $("#inputCustomerSurname").val(),
                CustomerPhone: $("#inputCustomerPhone").val(),
                CustomerAddress: $("#inputCustomerAddress").val(),
                CustomerMail: $("#inputCustomerEmail").val()
            },
            success: function (data) {
                $("tbody > tr").remove();
                createCustomerTable();
            }
        });
        $('.form-group > input').val('');
    });

    $("#btnDeleteCustomer").on("click", function () {
        $("input:checked").each(function () {
            $.ajax({
                url: "@Url.Action("DeleteCustomer", "Customer")",
                type: "POST",
                dataType: "json",
                data: { "id": this.parentElement.parentElement.getAttribute("customerid") },
                success: function () {
                    $("tbody > tr").remove();
                    createCustomerTable();
                }
            });
        });
    });

    $('.table tr').click(function (event) {
            if (event.target.type !== 'checkbox') {
                 $(':checkbox', this).trigger('click');
            }
        })
</script>

TurkTicaretCRM.TT.Mvc/Views/Customer/CustomerProfile.cshtml
@using TurkTicaretCRM.TT.Entities.Concrete;
@{
    ViewBag.Title = "CustomerProfile";
    var customer = ViewData["Customer"] as Customer;
}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="container">
                <label>Ad:</label>
                <label id="lblName">@customer.CustomerName</label>
            </div>
            <div class="container">
                <label>Soyad:</label>
                <label id="lblSurname">@customer.CustomerSurname</label>
            </div>
            <div class="container">
                <label>Telefon:</label>
                <label id="lblPhone">@customer.CustomerPhone</label>
            </div>
            <div class="container">
                <label>Adres:</label>
                <label id="lblAddress">@customer.CustomerAddress</label>
            </div>
            <div class="container">
                <label>Mail:</label>
                <label id="lblMail">@customer.CustomerMail</label>
            </div>
            <div class="row">
                <button>Ödeme</button>
                <button data-toggle="modal" data-target="#debitModal">Borç</button>
                <button>Güncelle</button>
            </div>
        </div>
        <div class="col">
            <div>
                Geçmiş Dönem Borçları
            </div>
            <table class="table table-hover" id="pastDebits">
                <thead>
                    <tr>
                        <td>Borç Tipi</td>
                        <td>Borç Toplamı</td>
                        <td>Borç Durumu</td>
                        <td>Kayıt Tarihi</td>
                        <td>Güncelleme Tarihi</td>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
    
    
</div>

<div class="modal fade" id="debitModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Borç Girişi</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <select id="debitTypes">

                    </select>
                </div>
                <div class="form-group"><input type="text" id="inputDebitTotalCost" class="form-control form-control-user" placeholder="Miktar Giriniz" required /></div>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <button id="btnAddDebitToCustomer" type="button" class="btn btn-primary" data-dismiss="modal">Ekle</button>
                    <button id="btnCloseCustomerModal" type="button" class="btn btn-primary" data-dismiss="modal">Kapat</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="debitActivityModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Borç Aktivitesi Ekle</h4>
            </div>
            <div class="modal-body">
                <div class="form-group"><input id="inputAmountPaid" class="form-control form-control-user" placeholder="Alınan Tutar" required /></div>
                <div class="form-group"><input id="inputComment" class="form-control form-control-user" placeholder="Yorum Giriniz" required /></div>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <button id="btnAddDebitActivity" type="button" class="btn btn-primary" data-dismiss="modal">Ekle</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Kapat</button>
                </div>

            </div>
        </div>
    </div>
</div>

<script>
    var currentCustomerDebitID;
    $(document).ready(function () {
        $.ajax({
            url: "@Url.Action("GetAllDebitsByCustomerId", "DebitManage")",
            type: "GET",
            dataType: "json",
            data: { id: @customer.CustomerID},
            success: function (result) {
                $.each(result, function (i, item) {
                    debugger;
                    $("#pastDebits").append($("<tr>").append(
                        $("<td>").text(item.DebitID),
                        $("<td>").text(item.DebitTotal),
                        $("<td>").text(function () {
                            if (item.CustomerDebitStatus === false) {
                                return "Ödendi";
                            }
                            else { return "Açık";}
                        }),
                        $("<td>").text(new Date(parseInt(item.RegistrationDate.substr(6))).toLocaleDateString("tr-TR")),
                        $("<td>").text(new Date(parseInt(item.UpdateDate.substr(6))).toLocaleDateString("tr-TR"))
                    ).attr("customerDebitId", item.CustomerDebitID).click(function () {
                        currentCustomerDebitID = item.CustomerDebitID;
                    })).attr("data-toggle", "modal").attr("data-target", "#debitActivityModal");
                })
            }
        })
    })

    $("#debitModal").ready(function () {
        $.ajax({
            url: "@Url.Action("GetAllDebits", "DebitType")",
            type:"GET",
            dataType: "json",
            success: function (data) {
                $.each(data,function (i, item) {
                    $("#debitTypes").append("<option id="+ item.DebitID +">" + item.DebitReason + "</option>");
                })
            }
        })

        $.ajax({
            
        })
    })

    $("#btnAddDebitToCustomer").on("click", function () {
        $.ajax({
            type: "POST",
            url: "@Url.Action("AddDebit", "DebitManage")",
            dataType: "json",
            data: {
                CustomerID: @customer.CustomerID,
                DebitID: $("option:selected").attr("id"),
                DebitReason: $("option:selected").val(),
                DebitTotal: $("#inputDebitTotalCost").val(),
                Debit: {DebitID: $("option:selected").attr("id"), DebitReason: $("option:selected").val()}
            },
            success: function () {
                location.reload();
            }
        })
    })

    $("#btnAddDebitActivity").on("click", function () {
        $.ajax({
            url: "@Url.Action("UpdateCustomerDebitWithActivity","DebitManage")",
            type: "POST",
            dataType: "json",
            data: {
                CustomerDebitID: currentCustomerDebitID,
                DiscountTotal: $("#inputAmountPaid").val(),
                Comment: $("#inputComment").val(),
                ActivityDate: new Date().toUTCString()
                },
            success: function () {
                location.reload();
            }
        })
    })
</script>

TurkTicaretCRM.TT.Mvc/Views/DebitManage/DebitManage.cshtml
@{
    ViewBag.Title = "DebitManage";
}

<table id="customerTable" class="table table-hover">
    <thead>
        <tr>
            <td>Ad</td>
            <td>Soyad</td>
            <td>Telefon Numarası</td>
            <td>Adres</td>
            <td>Kayıt Tarihi</td>
        </tr>
    </thead>
    <tbody>

    </tbody>
</table>

<script>
     $(document).ready(function () {
        $("tbody > tr").remove();
        createCustomerTable();
    });
    function createCustomerTable() {
        $("tbody > tr").remove();
        $.ajax({
            url: "@Url.Action("GetAllCustomers","Customer")",
            type: "GET",
            dataType: "json",
            success: function (data) {
                $.each(data, function (i, item) {
                    var $tr = $('<tr>').click(function () {
                        window.location.href = "@Url.Action("CustomerProfile", "Customer")?id=" + this.getAttribute("customerid"); 
                    }).append(
                        $('<td>').text(item.CustomerName),
                        $('<td>').text(item.CustomerSurname),
                        $('<td>').text(item.CustomerAddress),
                        $('<td>').text(item.CustomerPhone),
                        $('<td>').text(new Date(parseInt(item.RegistrationDate.substr(6))).toLocaleDateString())
                    ).attr("customerID",item.CustomerID).appendTo("#customerTable");
                });
            }
        })
    }

    $(document).ready(function () {
        $('.table tr').click(function (event) {
            if (event.target.type !== 'checkbox') {
                 $(':checkbox', this).trigger('click');
            }
           
        })
    })
</script>

TurkTicaretCRM.TT.Mvc/Views/DebitType/DebitTypeManage.cshtml
@{
    ViewBag.Title = "DebitTypeManage";
}

    <div class="container-fluid">
        <!--AddCustomer Button Here-->
        <div class="card-group">
            <div data-toggle="modal" data-target="#debitTypeModel">
                <a href="#" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                        <i class="fas fa-flag"></i>
                    </span>
                    <span class="text">Borç Tipi Ekle</span>
                </a>
            </div>
        </div>

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Borç Tipleri Tablosu</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-bordered dataTable" id="dataTable" width="50%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 38px;">Tip ID</th>
                                            <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 68px;">Borç Tipi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>

        </div>
    </div>

    <div class="modal fade" id="debitTypeModel" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Borç Tipi Ekle</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group"><input id="inputDebitType" class="form-control form-control-user" placeholder="Borç Tipi" required /></div>
                </div>
                <div class="modal-footer">
                    <div class="row">
                        <button id="btnAddDebitType" type="button" class="btn btn-primary" data-dismiss="modal">Ekle</button>
                        <button id="btnCloseDebitTypeModal" type="button" class="btn btn-primary" data-dismiss="modal">Kapat</button>
                    </div>

                </div>
            </div>
        </div>
    </div>
<script>
    $(document).ready(function () {
        $.ajax({
            url: "@Url.Action("GetAllDebits","DebitType")",
            type: "GET",
            dataType: "json",
            success: function (data) {
                $.each(data, function (i, item) {
                    var $tr = $('<tr>').append(
                        $('<td>').text(item.DebitID),
                        $('<td>').text(item.DebitReason)
                    ).attr("debittypeid",item.CustomerID).appendTo("#dataTable"); //.appendTo('#records_table');
                    
                });
            }
        })
    });

    $("#btnAddDebitType").on("click", function () {
        $.ajax({
            url: "@Url.Action("AddDebitType","DebitType")",
            type: "POST",
            dataType: "json",
            data: {
                DebitReason : $("#inputDebitType").val()
            },
            success: function (data) {

            }
        });
    });
</script>

TurkTicaretCRM.TT.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="~/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="~/Content/vendor/datatables/dataTables.bootstrap4.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Content/css/sb-admin-2.min.css" rel="stylesheet">
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/vendor/datatables/jquery.dataTables.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/vendor/jquery-easing/jquery.easing.min.js"></script>

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a id="sideBarTopic" class="sidebar-brand d-flex align-items-center justify-content-center" href="#" onclick="sidebarToggle()">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Turk Ticaret</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Home")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("CustomerManage","Customer")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Müşteri Yönetimi</span>
                </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("DebitTypeManage", "DebitType")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Borç Tipi Ekle</span>
                </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("DebitManage","DebitManage")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Borç Yönetimi</span>
                </a>
            </li>

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Turk Ticaret 2019</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    
    <script src="~/Content/js/sb-admin-2.min.js"></script>

</body>
</html>

<script>
    function sidebarToggle() {
        $("body").toggleClass("sidebar-toggled");
    $(".sidebar").toggleClass("toggled");
    if ($(".sidebar").hasClass("toggled")) {
      $('.sidebar .collapse').collapse('hide');
    };
    };
</script>